### Add company
POST http://localhost:8888/api/v1/company/add
Content-Type: application/json

{
  "name": "atlassian",
  "code": "team",
  "country": "usa",
 "website": "www.atlassian.com",
  "phone": "33353333"
}

### Search company

GET http://localhost:8888/api/v1/company/search?country=usa

### Edit company

POST http://localhost:8888/api/v1/company/edit?name=netflix
Content-Type: application/json

{
  "country": "zz"
}

### Delete company

GET http://localhost:8888/api/v1/company/delete?country=usa
